# Generated by Django 4.2.2 on 2023-06-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamam_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
