# Generated by Django 4.2.2 on 2023-06-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamam_app', '0003_xboxgame'),
    ]

    operations = []
