# Generated by Django 4.1.7 on 2023-04-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EpicGameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=250)),
                ('platforms', models.JSONField()),
                ('price_now', models.PositiveIntegerField()),
                ('flag_is_discount', models.BooleanField()),
                ('discount', models.PositiveIntegerField()),
                ('price_past', models.PositiveIntegerField()),
                ('timestrap', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PsAllModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=100)),
                ('platforms', models.JSONField()),
                ('base_price', models.PositiveIntegerField()),
                ('discounted_price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('is_free', models.BooleanField()),
                ('is_exclusive', models.BooleanField()),
                ('is_tied_to_subscription', models.BooleanField()),
                ('img', models.CharField(max_length=250)),
                ('timestrap', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PsDealsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=100)),
                ('platforms', models.JSONField()),
                ('base_price', models.PositiveIntegerField()),
                ('discounted_price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('is_free', models.BooleanField()),
                ('is_exclusive', models.BooleanField()),
                ('is_tied_to_subscription', models.BooleanField()),
                ('img', models.CharField(max_length=250)),
                ('timestrap', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteamGameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('game_link', models.CharField(max_length=250)),
                ('img', models.CharField(max_length=250)),
                ('platforms', models.JSONField()),
                ('release_date', models.CharField(max_length=100)),
                ('price_now', models.PositiveIntegerField()),
                ('flag_is_discount', models.BooleanField()),
                ('discount', models.PositiveIntegerField()),
                ('price_past', models.PositiveIntegerField()),
                ('flag_inner_prices', models.BooleanField()),
                ('inner_prices', models.JSONField()),
                ('timestrap', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='XboxGameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xbox_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=250)),
                ('platforms', models.JSONField()),
                ('release_date', models.CharField(max_length=100)),
                ('price_now', models.PositiveIntegerField()),
                ('flag_is_discount', models.BooleanField()),
                ('discount', models.PositiveIntegerField()),
                ('price_past', models.PositiveIntegerField()),
            ],
        ),
    ]
