# Generated by Django 4.1.7 on 2023-04-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpicGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=250)),
                ('platforms', models.JSONField()),
                ('price_now', models.PositiveIntegerField()),
                ('flag_is_discount', models.BooleanField()),
                ('discount', models.PositiveIntegerField()),
                ('price_past', models.PositiveIntegerField()),
                ('timestrap', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
        migrations.DeleteModel(
            name='EpicGameModel',
        ),
    ]
