# Generated by Django 4.2.2 on 2023-06-21 11:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Platform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='XboxGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('base_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('discount', models.SmallIntegerField()),
                ('img', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(default='playstation', limit_choices_to={'xbox_games': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='xbox_games', to='tamam_app.platform')),
            ],
            options={
                'verbose_name': 'Xbox game',
                'db_table': 'xbox_games',
            },
        ),
        migrations.CreateModel(
            name='SteamGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('base_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('discount', models.SmallIntegerField()),
                ('img', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steam_games', to='tamam_app.platform')),
            ],
            options={
                'verbose_name': 'Steam game',
                'db_table': 'steam_games',
            },
        ),
        migrations.CreateModel(
            name='PlaystationGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('base_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('discount', models.SmallIntegerField()),
                ('img', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playstation_games', to='tamam_app.platform')),
            ],
            options={
                'verbose_name': 'Playstation game',
                'db_table': 'playstation_games',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.SlugField(max_length=255, unique=True)),
                ('titles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('base_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('discount', models.SmallIntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tamam_app.platform')),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
    ]
