# Generated by Django 4.2.2 on 2023-06-14 11:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tamam_app', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayStationGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('base_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('discount', models.SmallIntegerField()),
                ('img', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'playstation_games',
            },
        ),
        migrations.CreateModel(
            name='SteamGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('base_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('discount', models.SmallIntegerField()),
                ('img', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'steam_games',
            },
        ),
        migrations.CreateModel(
            name='XboxGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('base_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('discount', models.SmallIntegerField()),
                ('img', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'xbox_games',
            },
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='xboxgame',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xbox_games', to='tamam_app.platform'),
        ),
        migrations.AddField(
            model_name='steamgame',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steam_games', to='tamam_app.platform'),
        ),
        migrations.AddField(
            model_name='playstationgame',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playstation_games', to='tamam_app.platform'),
        ),
    ]
