# Generated by Django 4.2.2 on 2023-06-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tamam_app', '0003_playstationgame_steamgame_xboxgame_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'managed': False, 'verbose_name': 'Platform'},
        ),
        migrations.AlterModelOptions(
            name='playstationgame',
            options={'verbose_name': 'Playstation game'},
        ),
        migrations.AlterModelOptions(
            name='steamgame',
            options={'verbose_name': 'Steam game'},
        ),
        migrations.AlterModelOptions(
            name='xboxgame',
            options={'verbose_name': 'Xbox game'},
        ),
        migrations.AlterField(
            model_name='xboxgame',
            name='platform',
            field=models.ForeignKey(default='playstation', limit_choices_to={'xbox_games': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='xbox_games', to='tamam_app.platform'),
        ),
    ]
